version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  db:
    image: mysql:8.0
    restart: always
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: challenge

  app:
    build: .
    restart: always
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/challenge?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dev
      SPRING_DATASOURCE_WRITER_URL: jdbc:mysql://db:3306/challenge?createDatabaseIfNotExist=true
