networks:
  app-network:
    driver: bridge

services:
  db:
    image: mysql:8.0
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pdev"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: challenge

  app:
    build: .
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # Using wget as curl is not available in alpine image
      test: ["CMD", "wget", "-O", "/tmp/health", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 5
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/challenge?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dev
      SPRING_DATASOURCE_WRITER_URL: jdbc:mysql://db:3306/challenge?createDatabaseIfNotExist=true
