deploy:
  restapi:
    name: restapi-deploy
    image: restapi
    repository: ankur512512
    pullPolicy: IfNotPresent
    tag: 13ec2b36a15acf163dfab82a3fafdb3ba2795c68
    labels:
      app: restapi
    app_port: 8080
    db_hostname: db-mysql
    db_port: 3306
    db_database: challenge
    db_username: root
    db_password_secret_name: db-mysql
    db_password_secret_key: mysql-root-password
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    readinessProbe:
      path: /actuator/health
    livenessProbe:
      path: /actuator/health
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000
service:
  restapi:
    name: restapi-service
    servicePort: 80
    type: ClusterIP
serviceAccount:
  create: true
  name: app-account-default
  namespace: default
hpa:
  enabled: true
  name: app-restapi-hpa
  labels:
    app: restapi
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilization: 70
  targetMemoryUtilization: 80
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
nodeSelector: {}
tolerations: []
affinity: {}
