apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.restapi.name }}
spec:
  selector:
    {{- toYaml .Values.deploy.restapi.labels | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.restapi.servicePort }}
      targetPort: {{ .Values.deploy.restapi.app_port }}
  type: {{ .Values.service.restapi.type }}
