name: PR-check

on:
  pull_request:
    branches:
    - main
    paths:
    - 'Dockerfile'
    - 'app/**'

jobs:
  pr-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build -t ankur512512/restapi:"$GITHUB_SHA" .
          docker images

      - name: Run Trivy vulnerability scanner for the image
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DISABLE_VEX_NOTICE: true
        with:
          image-ref: 'ankur512512/restapi:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
